config/routes.rb
Rails.application.routes.draw do
#-------------------------------------------------------------------------------    
#Main resources
  resources :assignments
  resources :stores
  resources :employees
  resources :flavors
  resources :jobs
  resources :shifts
  resources :sessions
#-------------------------------------------------------------------------------    
#Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

#-------------------------------------------------------------------------------    
#Routes user needs
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'session/current_user_info' => 'sessions#current_user_info', :as => :view_current_user

#-------------------------------------------------------------------------------    
#The root url
  root :to => 'home#home'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
# Callbacks
  before_save :reformat_phone
  before_validation :reformat_ssn
  before_destroy :destroyable?
  after_destroy :delete_assignment_and_shifts
  after_rollback :delete_employee


  
  # Relationships
  has_one :user
  accepts_nested_attributes_for :user
  has_many :assignments
  has_many :stores, through: :assignments
  has_one :user, dependent: :destroy
  has_many :shifts, through: :assignments
  accepts_nested_attributes_for :user
  
  # Validations
  validates_presence_of :first_name, :last_name, :date_of_birth, :ssn, :role
  validates_date :date_of_birth, on_or_before: lambda { 14.years.ago }, on_or_before_message: "must be at least 14 years old"
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only", allow_blank: true
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: "should be 9 digits and delimited with dashes only"
  validates_inclusion_of :role, in: %w[admin manager employee], message: "is not an option"
  validates_uniqueness_of :ssn
  
  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :active,          -> { where(active: true) }
  scope :inactive,        -> { where(active: false) }
  scope :regulars,        -> { where(role: 'employee') }
  scope :managers,        -> { where(role: 'manager') }
  scope :admins,          -> { where(role: 'admin') }
  scope :alphabetical,    -> { order('last_name, first_name') }
  
  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end
  
  def current_assignment
    curr_assignment = self.assignments.select{|a| a.end_date.nil?}
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end
  
  def over_18?
    date_of_birth < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end

  
  # Misc Constants
  ROLES_LIST = [['Employee', 'employee'],['Manager', 'manager'],['Administrator', 'admin']]
  
  
  # Callback code  (NOT DRY!!!)
  # -----------------------------
   #private
   def reformat_phone
     phone = self.phone.to_s  # change to string in case input as all numbers 
     phone.gsub!(/[^0-9]/,"") # strip all non-digits
     self.phone = phone       # reset self.phone to new string
   end
   def reformat_ssn
     ssn = self.ssn.to_s      # change to string in case input as all numbers 
     ssn.gsub!(/[^0-9]/,"")   # strip all non-digits
     self.ssn = ssn           # reset self.ssn to new string
   end 
   
    def destroyable?
        @destroyable = self.shifts.past.empty?
    end
    
    def make_inactive
        self.update_attribute(:active, false) if !@destroyable.nil? && @destroyable == false
        @destroyable = nil
    end
    
    def delete_assignment_and_shifts
      if @destroyable
      @new_shifts = self.shifts.upcoming
      @new_shifts.each {|x| x.destroy} unless @new_shifts.empty?
      self.current_assignment.delete unless self.current_assignment.nil?
      end
      @destroyable = nil
    end
    def delete_employee
      
      if !@destroyable.nil? && @destroyable == false
        @new_shifts = self.shifts.upcoming
        @new_shifts.each {|x| x.destroy} unless @new_shifts.empty?
        current_assignment = self.current_assignment    
        unless current_assignment.nil?
          current_assignment.update_attribute(:end_date, Date.current)
        end
      end
      @destroyable = nil
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  
  def index
    @active_employees = Employee.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_employees = Employee.inactive.alphabetical.paginate(page: params[:page]).per_page(10)
    @admin_employees = Employee.admins.alphabetical.paginate(page: params[:page]).per_page(15)
    @manager_employees = Employee.managers.alphabetical.paginate(page: params[:page]).per_page(15)
    @regular_employees = Employee.regulars.alphabetical.paginate(page: params[:page]).per_page(15)

  end

  def show
    # get the assignment history for this employee
    @assignments = @employee.assignments.chronological.paginate(page: params[:page]).per_page(5)
    # get upcoming shifts for this employee (later)  
  end

  def new
    @employee = Employee.new
    @employee.build_user
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    
    if @employee.save
        respond_to do |format|
        format.html { redirect_to @employee, notice: "Successfully created #{@employee.proper_name}." }
        format.json { render :show, status: :created, location: @employee }
        end
      else
        render action: 'new'
      
    end
  end

  def update
   
      if @employee.update(employee_params)
        respond_to do |format|
          format.html { redirect_to @employee, notice: "Successfully updated #{@employee.proper_name}." }
          format.json { render :show, status: :ok, location: @store }
        end
      else
          format.html { render :edit }
          format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    
    
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Successfully removed #{@employee.proper_name} from the AMC system." }
      format.json { head :no_content }
    end
    
  end

  private
  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :ssn, :date_of_birth, :role, :phone, :active, user_attributes: [:id, :email, :password])
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="input-field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>
  
  <div class="input-field">
  <%= form.fields_for :user do |field|%>
    <%= field.label "Email" %>
    <%= field.text_field :email %>
  </div>
  <div class="input-field">
    <%= field.label "Password" %>
    <%= field.password_field :password %>
  </div>
  <% end %>
  
  <div class="input-field">
    <%= form.label :ssn %>
    <%= form.text_field :ssn %>
  </div>

  <div class="input-field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth , :order => [:year, :month, :day], :start_year => 1980, :end_year => Time.now.year - 18 %>
  </div>

  <div class="input-field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
 
  <div class="input-field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="input-field">
    <%= form.label :active %>
    <%= form.select :active, [['Yes', true], ['No',false]] %>
  </div>
  
  <div class="actions">
    <%= form.submit :class=>"waves-effect waves-light btn green" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>
<br>
<%= link_to 'Show', @employee, :class => "btn-large waves-effect waves-light light-green" %>

<%= link_to 'Back', employees_path, :class => "btn-large waves-effect waves-light blue" %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#test1">Active Employees</a></li>
      <li class="tab col s3"><a href="#test2">Inactive Employees</a></li>
      <li class="tab col s3"><a href="#test4">Managers</a></li>
      <li class="tab col s3"><a href="#test5">Regular Employees</a></li>
    </ul>
  </div>
    
  <div id="test1" class="col s12">
    <% if (!@active_employees.nil?) then %>
    <table class= "striped">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Role</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% 
        @active_employees.each do |employee| %>
          <tr>
            <td><%= employee.first_name %></td>
            <td><%= employee.last_name %></td>
            <td><%= employee.role %></td>
            <td><%= link_to 'Show', employee_path(employee), :class=> "waves-effect waves-light btn light-green" %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee), :class=> "waves-effect waves-light btn light-blue" %></td>
            <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', data: { confirm: 'Are you sure?' }, method: :delete, :class=> "waves-effect waves-light btn red" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%end%>
  </div>
    <div id="test2" class="col s12">
      <% if (!@inactive_employees.nil?) then %>
      <table class = "striped">
        <thead>
          <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Role</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% 
          @inactive_employees.each do |employee| %>
            <tr>
              <td><%= employee.first_name %></td>
              <td><%= employee.last_name %></td>
              <td><%= employee.role %></td>
              <td><%= link_to 'Show', employee_path(employee), :class=> "waves-effect waves-light btn light-green" %></td>
              <td><%= link_to 'Edit', edit_employee_path(employee), :class=> "waves-effect waves-light btn light-blue" %></td>
              <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', data: { confirm: 'Are you sure?' }, method: :delete, :class=> "waves-effect waves-light btn red" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<%end%>
  <div id="test4" class="col s12">
    <% if (!@manager_employees.nil?) then %>
    <table class= "striped">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Role</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% 
        @manager_employees.each do |employee| %>
          <tr>
            <td><%= employee.first_name %></td>
            <td><%= employee.last_name %></td>
            <td><%= employee.role %></td>
            <td><%= link_to 'Show', employee_path(employee), :class=> "waves-effect waves-light btn light-green" %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee), :class=> "waves-effect waves-light btn light-blue" %></td>
            <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', data: { confirm: 'Are you sure?' }, method: :delete, :class=> "waves-effect waves-light btn red" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%end%>
  </div>

  <div id="test5" class="col s12">
    <% if (!@regular_employees.nil?) then %>
    <table class= "striped">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>Role</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <%@regular_employees.each do |employee| %>
          <tr>
            <td><%= employee.first_name %></td>
            <td><%= employee.last_name %></td>
            <td><%= employee.role %></td>
            <td><%= link_to 'Show', employee_path(employee), :class=> "waves-effect waves-light btn light-green" %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee), :class=> "waves-effect waves-light btn light-blue" %></td>
            <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', data: { confirm: 'Are you sure?' }, method: :delete, :class=> "waves-effect waves-light btn red" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%end%>
  </div>

</div>

<br>
<%= link_to 'New Employee', new_employee_path, :class=> "waves-effect waves-light btn green" %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>
<br>
<%= link_to 'Back', employees_path, :class => "btn-large waves-effect waves-light blue" %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<table class = "striped">
  <tbody>
    <tr>
      <td>First name:</td>
      <td><%= @employee.first_name %></td>
    </tr>
    <tr>
      <td>Last name:</td>
      <td><%= @employee.last_name %></td>
    </tr>
    <tr>
      <td>SSN:</td>
      <td><%= @employee.ssn %></td>
    </tr>
    <tr>
      <td>Date of birth:</td>
      <td><%= @employee.date_of_birth %></td>
    </tr>
    <tr>
      <td>Phone:</td>
      <td><%= @employee.phone %></td>
    </tr>
    <tr>
      <td>Role:</td>
      <td><%= @employee.role %></td>
    </tr>
    <tr>
      <td>Active:</td>
      <td><%= @employee.active %></td>
    </tr>
  </tbody>
</table>
<br>
<%= link_to 'Edit', edit_employee_path(@employee), :class => "btn-large waves-effect waves-light black-text yellow accent-3" %>

<%= link_to 'Back', employees_path, :class => "btn-large waves-effect waves-light blue" %>