config/routes.rb
Rails.application.routes.draw do
#-------------------------------------------------------------------------------    
#Main resources
  resources :assignments
  resources :stores
  resources :employees
  resources :flavors
  resources :jobs
  resources :shifts
  resources :sessions
#-------------------------------------------------------------------------------    
#Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

#-------------------------------------------------------------------------------    
#Routes user needs
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'session/current_user_info' => 'sessions#current_user_info', :as => :view_current_user

#-------------------------------------------------------------------------------    
#The root url
  root :to => 'home#home'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
# Callbacks
  before_save :reformat_phone
  before_destroy :destroyable?
  after_rollback :make_inactive
  
  
  # Relationships
  has_many :assignments
  has_many :employees, through: :assignments  
  has_many :shifts, through: :assignments
  has_many :store_flavors
  has_many :flavors, through: :store_flavors
  
  # Validations
  # make sure required fields are present
  validates_presence_of :name, :street, :zip
  # if state is given, must be one of the choices given (no hacking this field)
  validates_inclusion_of :state, :in => %w[PA OH WV], message: "is not an option"
  # if zip included, it must be 5 digits only
  validates_format_of :zip, with: /\A\d{5}\z/, message: "should be five digits long"
  # phone can have dashes, spaces, dots and parens, but must be 10 digits
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  # make sure stores have unique names
  validates_uniqueness_of :name
  
  # Scopes
  scope :alphabetical, -> { order('name') }
  scope :active,       -> { where(active: true) }
  scope :inactive,     -> { where(active: false) }
  
  
  # Misc Constants
  STATES_LIST = [['Ohio', 'OH'],['Pennsylvania', 'PA'],['West Virginia', 'WV']]
  
  
  # Callback code
  # -----------------------------
  private
  # We need to strip non-digits before saving to db
  def reformat_phone
    phone = self.phone.to_s  # change to string in case input as all numbers 
    phone.gsub!(/[^0-9]/,"") # strip all non-digits
    self.phone = phone       # reset self.phone to new string
  end
 
  def destroyable?
        self.errors.add(:base, "Cannot Delete flavors")
        throw(:abort)
  end
    
  def make_inactive
    self.update_attribute(:active, false)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @active_stores = Store.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_stores = Store.inactive.alphabetical.paginate(page: params[:page]).per_page(10)  
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @current_assignments = @store.assignments.current.by_employee.paginate(page: params[:page]).per_page(8)
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :street, :city, :state, :zip, :phone, :active)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="input-field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="input-field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="input-field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="input-field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="input-field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="input-field">
    <%= form.label :active %>
    <%= form.select :active, [['Yes', true], ['No',false]] %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"waves-effect waves-light btn green" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<br>
<%= link_to 'Show', @store, :class => "btn-large waves-effect waves-light light-green" %>

<%= link_to 'Back', stores_path, :class => "btn-large waves-effect waves-light blue" %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#test1">Active stores</a></li>
      <li class="tab col s3"><a href="#test2">Inactive stores</a></li>
    </ul>
  </div>
    
  <div id="test1" class="col s12">
    <% if (!@active_stores.nil?) then %>
    <table class= "striped">
      <thead>
        <tr>
          <th>Store name</th>
          <th>City</th>
          <th>Phone</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% 
        @active_stores.each do |store| %>
          <tr>
            <td><%= store.name %></td>
            <td><%= store.city %></td>
            <td><%= store.phone %></td>
            <td><%= link_to 'Show', store_path(store), :class=> "waves-effect waves-light btn light-green" %></td>
            <td><%= link_to 'Edit', edit_store_path(store), :class=> "waves-effect waves-light btn light-blue" %></td>
            <td><%= link_to 'Destroy', store, confirm: 'Are you sure?', data: { confirm: 'Are you sure?' }, method: :delete, :class=> "waves-effect waves-light btn red" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%end%>
  </div>
    <div id="test2" class="col s12">
      <% if (!@inactive_stores.inactive.nil?) then %>
      <table class = "striped">
        <thead>
          <tr>
            <th>store</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% 
          @inactive_stores.each do |store| %>
            <tr>
              <td><%= store.name %></td>
              <td><%= store.city %></td>
              <td><%= store.phone %></td>
              <td><%= link_to 'Show', store_path(store), :class=> "waves-effect waves-light btn light-green" %></td>
              <td><%= link_to 'Edit', edit_store_path(store), :class=> "waves-effect waves-light btn light-blue" %></td>
              <td><%= link_to 'Destroy', store, confirm: 'Are you sure?', data: { confirm: 'Are you sure?' }, method: :delete, :class=> "waves-effect waves-light btn red" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%end%>
</div>

<br>
<%= link_to 'New store', new_store_path, :class=> "waves-effect waves-light btn green" %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<br>
<%= link_to 'Back', stores_path, :class => "btn-large waves-effect waves-light blue" %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<table class = "striped">
  <tbody>
    <tr>
      <td>Name:</td>
      <td><%= @store.name %></td>
    </tr>
    <tr>
      <td>Street:</td>
      <td><%= @store.street %></td>
    </tr>
    <tr>
      <td>City:</td>
      <td><%= @store.city %></td>
    </tr>
    <tr>
      <td>State:</td>
      <td><%= @store.state %></td>
    </tr>
    <tr>
      <td>Zip:</td>
      <td><%= @store.name %></td>
    </tr>
    <tr>
      <td>Phone:</td>
      <td><%= @store.name %></td>
    </tr>
    <tr>
      <td>Active:</td>
      <td><%= @store.active%></td>
    </tr>
    
  </tbody>
</table>
<br>

<%= link_to 'Edit', edit_store_path(@store), :class => "btn-large waves-effect waves-light black-text yellow accent-3" %>

<%= link_to 'Back', stores_path, :class => "btn-large waves-effect waves-light blue" %>