config/routes.rb
Rails.application.routes.draw do
#-------------------------------------------------------------------------------    
#Main resources
  resources :assignments
  resources :stores
  resources :employees
  resources :flavors
  resources :jobs
  resources :shifts
  resources :sessions
#-------------------------------------------------------------------------------    
#Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

#-------------------------------------------------------------------------------    
#Routes user needs
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'session/current_user_info' => 'sessions#current_user_info', :as => :view_current_user

#-------------------------------------------------------------------------------    
#The root url
  root :to => 'home#home'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_address_info.html.erb
  <%= store.street %><br />
  <%= store.city %>, <%= store.state %> <%= store.zip %>

app/views/partials/_display_form.html.erb
<div class="row">
  <div class="col s8">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %> radius">
    <a href="#" class="close">&times;</a>
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer class = "page-footer">
	<div class="row valign-wrapper">
		<div class = "col s3">
	    	
	    </div>
		<div class="col s6 center">
	        <ul class="center">
	        	<%= link_to 'Home', home_path, :class => 'white-text text-accent-3' %>&nbsp;&nbsp;&nbsp;&nbsp;
	  			<%= link_to 'About the Creamery', about_path, :class => 'white-text text-accent-3' %>&nbsp;&nbsp;&nbsp;&nbsp;
				<%= link_to 'Contact Us', contact_path, :class => 'white-text text-accent-3' %>&nbsp;&nbsp;&nbsp;&nbsp;
				<%= link_to 'Privacy Policy', privacy_path, :class => 'white-text text-accent-3' %>
	    	</ul>
	    </div>
    	<div class="col s3 valign center">
          <% if current_user!=nil %>
          <%= link_to "click here to logout", logout_path, :class => 'btn white red-text text-accent-3' %>
          <% end %>
    	</div>
    </div>
	<div class="footer-copyright">
		Webmaster: <%= mail_to("aedward@andrew.cmu.edu", "ANDREW EDWARD", encode: "javascript", :class => 'white-text text-accent-3') %> 
		&nbsp;&nbsp;&copy 2019
	</div>
</footer>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
  <!-- <i class="fa fa-plus"></i> -->
  &nbsp;Add a New <%= model_name.capitalize %>
<% end %>

app/views/partials/_index_structure_2.html.erb
<div class="row">
  <div class="col s9">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="col s3">
    <!-- Add a button for new instances of object -->
    <%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
      <!-- <i class="fa fa-plus"></i> -->
      &nbsp;Add a New <%= model_name.capitalize %>
    <% end %>
  </div>
</div>

app/views/partials/_nav.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation"> 
    <section class="top-bar-section">
      <ul class="left">
        <!-- link to home -->
        <li><%= link_to "Home", home_path %></li>

        <!-- options for stores -->
        <li class="has-dropdown">
          <%= link_to "Stores", stores_path %>
          <ul class="dropdown">
            <li><%= link_to "Store List", stores_path %></li>
            <li><%= link_to "Add a Store", new_store_path %></li>
          </ul>
        </li>

        <!-- options for employees -->
        <li class="has-dropdown">
          <%= link_to "Employees", employees_path %>
          <ul class="dropdown">
            <li><%= link_to "Employee List", employees_path %></li>
            <li><%= link_to "Add an Employee", new_employee_path %></li>
          </ul>
        </li>

        <!-- options for assignments -->
        <li class="has-dropdown">
          <%= link_to "Assignments", assignments_path %>
          <ul class="dropdown">
            <li><%= link_to "Assignments List", assignments_path %></li>
            <li><%= link_to "Create New Assignment", new_assignment_path %></li>
          </ul>
        </li>
      </ul>

    </section>
  </nav>
</div>

app/views/partials/_object_options.html.erb
  <% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

  <div class="form-actions">
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'button radius') do %>
      &nbsp;Display All <%= model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
    
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'button radius') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
    
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'button radius alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  </div>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="col s7">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="col s5">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "#{model_name}", object: @object}  %>