config/routes.rb
Rails.application.routes.draw do
#-------------------------------------------------------------------------------    
#Main resources
  resources :assignments
  resources :stores
  resources :employees
  resources :flavors
  resources :jobs
  resources :shifts
  resources :sessions
#-------------------------------------------------------------------------------    
#Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

#-------------------------------------------------------------------------------    
#Routes user needs
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'session/current_user_info' => 'sessions#current_user_info', :as => :view_current_user

#-------------------------------------------------------------------------------    
#The root url
  root :to => 'home#home'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def about
  end

  def privacy
  end

  def contact
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_general_home.html.erb
<!-- ------------------------------------------------------------------  -->


<div class = "row">
  <br/>
  <div class = "col s6 center">
    <h2>Welcome to A & M's Creamery System</h2>
  </div>
  <div class = "col s6 center">
  <img class = "responsive-img" style = "width: 30%" src = "https://image.flaticon.com/icons/svg/1090/1090918.svg">
  </div>
</div>

<% if current_user==nil%>
<br>
<div class = "row">
    <div class = "col s12">
        <%= link_to "click here to login", login_path, :class => 'btn red accent-3 white-text text-accent-3'%>
    </div>
</div>
<% end %>




<% if current_user!=nil && (current_user.role? :admin)%>
<div class = "row">
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/1732/1732803.svg">
      </div>
      <div class="card-content">
          <h4><strong><%= link_to "Stores", stores_path, :class => 'red-text text-accent-3' %></strong></h4>
        </div>
    </div>
  </div>
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/265/265674.svg">
      </div>
      <div class="card-content">
        <h4><strong><%= link_to "Employees", employees_path, :class => 'red-text text-accent-3' %></strong></h4>
      </div>
    </div>
  </div>
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/1617/1617719.svg">
      </div>
      <div class="card-content">
        <h4><strong><%= link_to "Assignments", assignments_path, :class => 'red-text text-accent-3' %></strong></h4>
      </div>
    </div>
  </div>
</div>

<div class = "row">
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/148/148982.svg">
      </div>
      <div class="card-content">
          <h4><strong><%= link_to "Shifts", shifts_path, :class => 'red-text text-accent-3' %></strong></h4>
        </div>
    </div>
  </div>
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/1651/1651622.svg">
      </div>
      <div class="card-content">
        <h4><strong><%= link_to "Jobs", jobs_path, :class => 'red-text text-accent-3' %></strong></h4>
      </div>
    </div>
  </div>
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/1732/1732785.svg">
      </div>
      <div class="card-content">
        <h4><strong><%= link_to "Flavors", flavors_path, :class => 'red-text text-accent-3' %></strong></h4>
      </div>
    </div>
  </div>
</div>
<% end %>

<% if current_user!=nil && (current_user.role? :manager)%>
<div class = "row">
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/1732/1732803.svg">
      </div>
      <div class="card-content">
          <h4><strong><%= link_to "Stores", stores_path, :class => 'red-text text-accent-3' %></strong></h4>
        </div>
    </div>
  </div>
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/265/265674.svg">
      </div>
      <div class="card-content">
        <h4><strong><%= link_to "Employees", employees_path, :class => 'red-text text-accent-3' %></strong></h4>
      </div>
    </div>
  </div>
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/1617/1617719.svg">
      </div>
      <div class="card-content">
        <h4><strong><%= link_to "Assignments", assignments_path, :class => 'red-text text-accent-3' %></strong></h4>
      </div>
    </div>
  </div>
</div>
<div class = "row">
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/1732/1732785.svg">
      </div>
      <div class="card-content">
        <h4><strong><%= link_to "Flavors", flavors_path, :class => 'red-text text-accent-3' %></strong></h4>
      </div>
    </div>
  </div>
</div>
<% end %>

<% if current_user!=nil && (current_user.role? :employee) %>
<div class = "row">
  <div class = "col s4">
  </div>
  <div class = "col s4">
    <div class="card">
      <div class="card-image">
        <img src="https://image.flaticon.com/icons/svg/417/417777.svg">
      </div>
      <div class="card-content">
        <h4><strong><%= link_to "View your information", view_current_user_path, :class => 'red-text text-accent-3' %></strong></h4>
      </div>
    </div>
  </div>
  <div class = "col s4">
  </div>
</div>

<% end %>

<!-- ------------------------------------------------------------------  -->

app/views/home/about.html.erb
  <div class = "row">
    <h1>About A &amp; M Creamery</h1>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <div class = "col s6">
          <p class="flow-text"><strong>
    	  I scream, you scream, we all scream for ice cream!  Or at least that 
        is what we are led to believe.  The fact is few people scream for ice 
        cream, but truth be told, after trying some of the delectable treats at 
        our creamery, people literally beg for more.  Not only is it great ice 
        cream, but it is also a great place to work.  If you are interested in 
        ice cream and/or a job, just stop by one of our stores today.
        </strong></p>

    </div>
    <div class = "col s6">
      <img style = "width: 80%" src="https://image.flaticon.com/icons/svg/1205/1205759.svg">
    </div>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
  </div>
    

app/views/home/contact.html.erb
<h2>Contact A&M Creamery</h2>
		<p class="supertiny">&nbsp;</p>
		<div class = "col s12">
			<table class = "striped">
			<tr>
				<td>Webmaster:&nbsp;&nbsp;&nbsp;</td>
				<td>Andrew Edward</td>
			</tr>
			<tr>
				<td>Email:</td>
				<td>
				<%= mail_to("aedward@andrew.cmu.edu", "Andrew Edward*", :encode => "javascript") %> 
				</td>
			</tr>
			<tr>
				<td>Phone:</td>
				<td>97433118785</td>
			</tr>
		</table>

		<p class="note"><br></em></p>
			
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			<p>&nbsp;</p>
			
		</div>
		

app/views/home/home.html.erb
	<%= render :partial => 'general_home' %>

app/views/home/privacy.html.erb
<div class="row">
	<div class="col s12">
		<h2>A &amp; M Creamery Privacy Policy</h2>

		<p>The A &amp; M Creamery privacy policy is very simple, rarely  
			changes, and does not require a lawyer to understand it.  
			We will pounce on the opportunity to sell every bit of information 
			on you they have at our disposal.  We will gladly sell your address, 
			phone, email, age, name of pet, name of favorite superhero, color of 
			bunny slippers you wear at home, and the like, to any willing buyer 
			who will pay the big bucks.  (BTW, we <em>know</em> you wear bunny 
			slippers at home and we know what color they are.  You really have 
			no secrets from this crew.)  If you have sensitive information that 
			you don't want us to share with the world, then keep it to yourself 
			-- don't tell us.  
			<br><br>
			It's really that simple.
		</p>

		<p>&nbsp;</p>
		<p>&nbsp;</p>
		<p>&nbsp;</p>
	</div>
</div>